// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductManager.Models.DBContext;

#nullable disable

namespace ProductManager.Migrations.TransactionDB
{
    [DbContext(typeof(TransactionDBContext))]
    [Migration("20250402232441_InitialMigration-TransactionDBContext")]
    partial class InitialMigrationTransactionDBContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductManager.Models.Transaction", b =>
                {
                    b.Property<int>("idTransaction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTransaction"));

                    b.Property<string>("comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("idProduct")
                        .HasColumnType("int");

                    b.Property<int>("pieces")
                        .HasColumnType("int");

                    b.Property<int>("typeTransaction")
                        .HasColumnType("int");

                    b.HasKey("idTransaction");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
